version: '2'

networks:
  metricsnet:
    driver: bridge

volumes:
  metricsdata:
    driver: local

services:
  metricsdb:
    hostname: metricsdb
    image: postgres
    networks:
      - metricsnet
    ports:
      - '5432:5432'
    volumes:
      - metricsdata:/metricsdata
    env_file:
      - metrics.env
    environment:
      PGDATA: '/metricsdata'
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d  
