CREATE INDEX met1_idx on MET (repository, metrics_name, metrics_value);
CREATE INDEX metrics1_idx on METRICS (repository, metrics_name, metrics_value);
CREATE INDEX mmetrics1_idx on METRICSMILLION (repository, metrics_name, metrics_value);
CREATE INDEX met2_idx on MET (metrics_name, award_number, location, month, year, metrics_value);
CREATE INDEX metrics2_idx on METRICS (metrics_name, award_number, location, month, year, metrics_value);
CREATE INDEX mmetrics2_idx on METRICSMILLION (metrics_name, award_number, location, month, year, metrics_value);
CREATE INDEX met3_idx on MET (repository, metrics_name, year, metrics_value);
CREATE INDEX metrics3_idx on METRICS (repository, metrics_name, year, metrics_value);
CREATE INDEX mmetrics3_idx on METRICSMILLION (repository, metrics_name, year, metrics_value);
CREATE INDEX met4_idx on MET (repository, metrics_name, month, metrics_value);
CREATE INDEX metrics4_idx on METRICS (repository, metrics_name, month, metrics_value);
CREATE INDEX mmetrics4_idx on METRICSMILLION (repository, metrics_name, month,  metrics_value);
CREATE INDEX met5_idx on MET (repository, metrics_name, month, year, metrics_value);
CREATE INDEX metrics5_idx on METRICS (repository, metrics_name, month, year, metrics_value);
CREATE INDEX mmetrics5_idx on METRICSMILLION (repository, metrics_name, month, year,  metrics_value);
CREATE INDEX met6_idx on MET (repository, metrics_name, day, month, year, metrics_value);
CREATE INDEX metrics6_idx on METRICS (repository, metrics_name, day, month, year, metrics_value);
CREATE INDEX mmetrics6_idx on METRICSMILLION (repository, metrics_name, day, month, year, metrics_value);
CREATE INDEX met7_idx on MET (dataset_id, metrics_name, user_id, metrics_value);
CREATE INDEX metrics7_idx on METRICS (dataset_id, metrics_name, user_id,  metrics_value);
CREATE INDEX mmetrics7_idx on METRICSMILLION (dataset_id, metrics_name, user_id, metrics_value);
CREATE INDEX met8_idx on MET (dataset_id, metrics_name, month, year, metrics_value);
CREATE INDEX metrics8_idx on METRICS (dataset_id, metrics_name, month, year, metrics_value);
CREATE INDEX mmetrics8_idx on METRICSMILLION (dataset_id, metrics_name, month, year,  metrics_value);
CREATE INDEX met10_idx on MET (user_id, metrics_name, month, year, metrics_value);
CREATE INDEX metrics10_idx on METRICS (user_id, metrics_name , month, year, metrics_value);
CREATE INDEX mmetrics10_idx on METRICSMILLION (user_id, metrics_name, month, year,  metrics_value);
CREATE INDEX met11_idx on MET (repository, metrics_name, month, year, metrics_value);
CREATE INDEX metrics11_idx on METRICS (repository, metrics_name, month, year, metrics_value);
CREATE INDEX mmetrics11_idx on METRICSMILLION (repository, metrics_name, month, year,  metrics_value);
CREATE INDEX met12_idx on MET (award_number, metrics_name, month, year, metrics_value);
CREATE INDEX metrics12_idx on METRICS (award_number, metrics_name , month, year, metrics_value);
CREATE INDEX mmetrics12_idx on METRICSMILLION (award_number, metrics_name, month, year,  metrics_value);