CREATE INDEX met1_idx ON MET (repository, metrics_name, metrics_value);
CREATE INDEX metrics1_idx ON METRICS (repository, metrics_name, metrics_value);
CREATE INDEX mmetrics1_idx ON METRICSMILLION (repository, metrics_name, metrics_value);
CREATE INDEX met2_idx ON MET (metrics_name, award_number, location, month, year, metrics_value);
CREATE INDEX metrics2_idx ON METRICS (metrics_name, award_number, location, month, year, metrics_value);
CREATE INDEX mmetrics2_idx ON METRICSMILLION (metrics_name, award_number, location, month, year, metrics_value);
CREATE INDEX met3_idx ON MET (repository, metrics_name, year, metrics_value);
CREATE INDEX metrics3_idx ON METRICS (repository, metrics_name, year, metrics_value);
CREATE INDEX mmetrics3_idx ON METRICSMILLION (repository, metrics_name, year, metrics_value);
CREATE INDEX met4_idx ON MET (repository, metrics_name, month, metrics_value);
CREATE INDEX metrics4_idx ON METRICS (repository, metrics_name, month, metrics_value);
CREATE INDEX mmetrics4_idx ON METRICSMILLION (repository, metrics_name, month,  metrics_value);
CREATE INDEX met5_idx ON MET (repository, metrics_name, month, year, metrics_value);
CREATE INDEX metrics5_idx ON METRICS (repository, metrics_name, month, year, metrics_value);
CREATE INDEX mmetrics5_idx ON METRICSMILLION (repository, metrics_name, month, year,  metrics_value);
CREATE INDEX met6_idx ON MET (repository, metrics_name, day, month, year, metrics_value);
CREATE INDEX metrics6_idx ON METRICS (repository, metrics_name, day, month, year, metrics_value);
CREATE INDEX mmetrics6_idx ON METRICSMILLION (repository, metrics_name, day, month, year, metrics_value);
CREATE INDEX met7_idx ON MET (dataset_id, metrics_name, user_id, metrics_value);
CREATE INDEX metrics7_idx ON METRICS (dataset_id, metrics_name, user_id,  metrics_value);
CREATE INDEX mmetrics7_idx ON METRICSMILLION (dataset_id, metrics_name, user_id, metrics_value);
CREATE INDEX met8_idx ON MET (dataset_id, metrics_name, month, year, metrics_value);
CREATE INDEX metrics8_idx ON METRICS (dataset_id, metrics_name, month, year, metrics_value);
CREATE INDEX mmetrics8_idx ON METRICSMILLION (dataset_id, metrics_name, month, year,  metrics_value);
CREATE INDEX met10_idx ON MET (user_id, metrics_name, month, year, metrics_value);
CREATE INDEX metrics10_idx ON METRICS (user_id, metrics_name , month, year, metrics_value);
CREATE INDEX mmetrics10_idx ON METRICSMILLION (user_id, metrics_name, month, year,  metrics_value);
CREATE INDEX met11_idx ON MET (repository, metrics_name, month, year, metrics_value);
CREATE INDEX metrics11_idx ON METRICS (repository, metrics_name, month, year, metrics_value);
CREATE INDEX mmetrics11_idx ON METRICSMILLION (repository, metrics_name, month, year,  metrics_value);
CREATE INDEX met12_idx ON MET (award_number, metrics_name, month, year, metrics_value);
CREATE INDEX metrics12_idx ON METRICS (award_number, metrics_name , month, year, metrics_value);
CREATE INDEX mmetrics12_idx ON METRICSMILLION (award_number, metrics_name, month, year,  metrics_value);